/**
 * Словарь панели: ключ → три языка.
 * Основной — латышский; русский и английский переключаются в шапке.
 */
export const DICT: Record<string, { lv: string; en: string; ru: string }> = {
  "a.epohaProishozhdenie": { lv: "Laikmets / izcelsme", en: "Era / origin", ru: "Эпоха / происхождение" },
  "a.iliDobavitFoto": { lv: "…vai pievienot foto pēc tiešās saites", en: "…or add a photo by direct link", ru: "…или добавить фото по прямой ссылке" },
  "a.jpgPngIli": { lv: "JPG, PNG vai WEBP · var vairākus uzreiz · lielos attēlus saspiedīsim automātiski", en: "JPG, PNG or WEBP · several at once · large photos are compressed automatically", ru: "JPG, PNG или WEBP · можно сразу несколько · большие снимки сожмём автоматически" },
  "a.kVyplate": { lv: "Izmaksai", en: "For payout", ru: "К выплате" },
  "a.kartochkaSohranenaNo": { lv: "Kartīte saglabāta, bet tulkojums neizdevās", en: "Card saved, but translation failed", ru: "Карточка сохранена, но перевод не сработал" },
  "a.komissiyaPloschadki": { lv: "SOFA.LV komisijas maksa", en: "Platform commission", ru: "Комиссия площадки" },
  "a.kopiyaKartochkiProverte": { lv: "Kartītes kopija: pirms saglabāšanas pārbaudiet numuru un cenu.", en: "Copy of the card: check the number and price before saving.", ru: "Копия карточки: проверьте номер и цену перед сохранением." },
  "a.minimum6Simvolov": { lv: "vismaz 6 rakstzīmes", en: "at least 6 characters", ru: "минимум 6 символов" },
  "a.novyjParolPusto": { lv: "Jaunā parole (tukša — nemainīt)", en: "New password (blank — keep current)", ru: "Новый пароль (пусто — не менять)" },
  "a.oblozhka": { lv: "galvenais", en: "cover", ru: "обложка" },
  "a.panelSofaLv": { lv: "Panelis · SOFA.LV", en: "Panel · SOFA.LV", ru: "Панель · SOFA.LV" },
  "a.poOplachennymZakazam": { lv: "pēc apmaksātajiem pasūtījumiem", en: "for paid orders", ru: "по оплаченным заказам" },
  "a.prodanoNa": { lv: "Pārdots par", en: "Sold for", ru: "Продано на" },
  "a.prodazhPokaNet": { lv: "Pārdevumu vēl nav.", en: "No sales yet.", ru: "Продаж пока нет." },
  "a.russkij": { lv: "Krievu", en: "Russian", ru: "Русский" },
  "a.shveciyaXxVek": { lv: "Zviedrija · 20. gs.", en: "Sweden · 20th century", ru: "Швеция · XX век" },
  "a.spisokObnovlyaetsyaSam": { lv: "Saraksts atjaunojas automātiski ik pēc 30 sekundēm", en: "The list refreshes automatically every 30 seconds", ru: "Список обновляется сам каждые 30 секунд" },
  "a.status": { lv: "Statuss", en: "Status", ru: "Статус" },
  "a.summa": { lv: "Summa", en: "Amount", ru: "Сумма" },
  "a.tyanemDannyeSo": { lv: "Ielasām datus no lapas…", en: "Fetching data from the page…", ru: "Тянем данные со страницы…" },
  "a.udalitFoto": { lv: "Dzēst foto", en: "Delete photo", ru: "Удалить фото" },
  "a.vvoditeSleduyuschij": { lv: " · ievadiet nākamo", en: " · enter the next one", ru: " · вводите следующий" },
  "a.zagruzhaemProgress": { lv: " ? `Ielādējam ${progress}…` : ", en: " ? `Uploading ${progress}…` : ", ru: " ? `Загружаем ${progress}…` : " },
  "a.zakazyBezOplaty": { lv: "pasūtījumi bez apmaksas", en: "orders without payment", ru: "заказы без оплаты" },
  "a.zapolniteKartochkuHotya": { lv: "Aizpildiet kartīti vismaz vienā valodā", en: "Fill in the card in at least one language", ru: "Заполните карточку хотя бы на одном языке" },
  "cat.decor": { lv: "Dekors un keramika", en: "Decor & ceramics", ru: "Декор и керамика" },
  "cat.light": { lv: "Apgaismojums", en: "Lighting", ru: "Свет" },
  "cat.mirror": { lv: "Spoguļi", en: "Mirrors", ru: "Зеркала" },
  "cat.seating": { lv: "Mīkstās mēbeles", en: "Seating", ru: "Мягкая мебель" },
  "cat.storage": { lv: "Kumodes un glabāšana", en: "Chests & storage", ru: "Комоды и хранение" },
  "cat.table": { lv: "Galdi", en: "Tables", ru: "Столы" },
  "ed.add": { lv: "Pievienot", en: "Add", ru: "Добавить" },
  "ed.autoHint": { lv: "Tukšās valodas aizpildīsies automātiski, saglabājot", en: "Empty languages are filled in automatically on save", ru: "Пустые языки заполнятся автоматически при сохранении" },
  "ed.cancel": { lv: "Atcelt", en: "Cancel", ru: "Отмена" },
  "ed.cat": { lv: "Kategorija", en: "Category", ru: "Категория" },
  "ed.copyFrom": { lv: "Kopēt no", en: "Copy from", ru: "Скопировать из" },
  "ed.cover": { lv: "Iestatīt kā galveno", en: "Set as cover", ru: "Сделать обложкой" },
  "ed.desc": { lv: "Apraksts", en: "Description", ru: "Описание" },
  "ed.era": { lv: "Laikmets un izcelsme", en: "Era and origin", ru: "Эпоха и происхождение" },
  "ed.hide": { lv: "Paslēpt no skatloga", en: "Hide from the storefront", ru: "Скрыть с витрины" },
  "ed.newItem": { lv: "Jauna prece", en: "New item", ru: "Новый товар" },
  "ed.number": { lv: "Skatloga numurs", en: "Storefront number", ru: "Номер витрины" },
  "ed.photoUrl": { lv: "Saite uz foto", en: "Photo link", ru: "Ссылка на фото" },
  "ed.photos": { lv: "Fotogrāfijas", en: "Photos", ru: "Фотографии" },
  "ed.price": { lv: "Pārdošanas cena, €", en: "Sale price, €", ru: "Цена продажи, €" },
  "ed.remove": { lv: "Noņemt", en: "Remove", ru: "Убрать" },
  "ed.save": { lv: "Saglabāt", en: "Save", ru: "Сохранить" },
  "ed.saveNext": { lv: "Saglabāt un pievienot vēl", en: "Save and add another", ru: "Сохранить и добавить ещё" },
  "ed.saving": { lv: "Saglabā…", en: "Saving…", ru: "Сохранение…" },
  "ed.sold": { lv: "Pārdots", en: "Sold", ru: "Продано" },
  "ed.title": { lv: "Nosaukums", en: "Title", ru: "Название" },
  "ed.translate": { lv: "Tulkot", en: "Translate", ru: "Перевести" },
  "ed.translating": { lv: "Tulko…", en: "Translating…", ru: "Перевод…" },
  "f.big": { lv: "Lielāka summa", en: "Higher amount", ru: "Сумма больше" },
  "f.cheap": { lv: "Lētākie", en: "Lower price", ru: "Дешевле" },
  "f.new": { lv: "Vispirms jaunākie", en: "Newest first", ru: "Сначала новые" },
  "f.old": { lv: "Vispirms vecākie", en: "Oldest first", ru: "Сначала старые" },
  "f.reset": { lv: "Atiestatīt", en: "Reset", ru: "Сбросить" },
  "f.rich": { lv: "Dārgākie", en: "Higher price", ru: "Дороже" },
  "f.small": { lv: "Mazāka summa", en: "Lower amount", ru: "Сумма меньше" },
  "g.kartochkaISvyaz": { lv: "Kartīte un saikne ar iepriekšējiem pasūtījumiem pazudīs neatgriezeniski. Parasti pietiek ar arhīvu.", en: "The card and its link to past orders will be gone for good. The archive is usually enough.", ru: "Карточка и связь с прошлыми заказами исчезнут навсегда. Обычно достаточно архива." },
  "gd.allCats": { lv: "Visas kategorijas", en: "All categories", ru: "Все категории" },
  "gd.allSellers": { lv: "Visi pārdevēji", en: "All sellers", ru: "Все продавцы" },
  "gd.archTag": { lv: "arhīvā", en: "in the archive", ru: "в архиве" },
  "gd.archive": { lv: "Pārvietot uz arhīvu", en: "Move to archive", ru: "Убрать в архив" },
  "gd.archived": { lv: "Arhīvs", en: "Archive", ru: "Архив" },
  "gd.archived2": { lv: "Pārvietots uz arhīvu", en: "Moved to archive", ru: "Убрано в архив" },
  "gd.bulkArchived": { lv: "Pārvietoti uz arhīvu", en: "Moved to archive", ru: "Убраны в архив" },
  "gd.bulkCat": { lv: "Kategorija mainīta", en: "Category changed", ru: "Категория изменена" },
  "gd.bulkHidden": { lv: "Paslēpti no skatloga", en: "Hidden from the storefront", ru: "Скрыты с витрины" },
  "gd.bulkShown": { lv: "Parādīti skatlogā", en: "Shown on the storefront", ru: "Показаны на витрине" },
  "gd.bulkSold": { lv: "Atzīmēti kā pārdoti", en: "Marked as sold", ru: "Отмечены проданными" },
  "gd.catTo": { lv: "Kategorija →", en: "Category →", ru: "Категория →" },
  "gd.deleteFail": { lv: "Neizdevās izdzēst", en: "Delete failed", ru: "Не удалилось" },
  "gd.deleteForever": { lv: "Dzēst neatgriezeniski", en: "Delete forever", ru: "Удалить навсегда" },
  "gd.deleted": { lv: "Prece izdzēsta", en: "Item deleted", ru: "Товар удалён" },
  "gd.duplicate": { lv: "Dublēt", en: "Duplicate", ru: "Дублировать" },
  "gd.edit": { lv: "Labot", en: "Edit", ru: "Изменить" },
  "gd.editPrice": { lv: "Labot cenu", en: "Edit price", ru: "Изменить цену" },
  "gd.empty": { lv: "Nekas nav atrasts", en: "Nothing found", ru: "Ничего не найдено" },
  "gd.emptyHint": { lv: "Nomainiet statusa filtru vai notīriet meklēšanu.", en: "Change the status filter or clear the search.", ru: "Смените фильтр состояния или сбросьте поиск." },
  "gd.free": { lv: "Pārdošanā", en: "For sale", ru: "В продаже" },
  "gd.hid": { lv: "Paslēpts no skatloga", en: "Hidden from the storefront", ru: "Скрыт с витрины" },
  "gd.hidden": { lv: "Paslēptie", en: "Hidden", ru: "Скрыто" },
  "gd.hiddenTag": { lv: "paslēpts no skatloga", en: "hidden from the storefront", ru: "скрыто с витрины" },
  "gd.hide": { lv: "Paslēpt no skatloga", en: "Hide from the storefront", ru: "Скрыть с витрины" },
  "gd.hideShort": { lv: "Paslēpt", en: "Hide", ru: "Скрыть" },
  "gd.live": { lv: "Visi aktīvie", en: "All active", ru: "Все активные" },
  "gd.marked": { lv: "Atzīmēts kā pārdots", en: "Marked as sold", ru: "Отметили проданным" },
  "gd.noPhotoTag": { lv: "nav foto", en: "no photo", ru: "нет фото" },
  "gd.nophoto": { lv: "Bez foto", en: "No photo", ru: "Без фото" },
  "gd.notr": { lv: "Bez tulkojuma", en: "No translation", ru: "Без перевода" },
  "gd.photos": { lv: "foto", en: "photos", ru: "фото" },
  "gd.picked": { lv: "atlasīts", en: "selected", ru: "отмечено" },
  "gd.priceFail": { lv: "Cena nav saglabāta", en: "Price not saved", ru: "Цена не сохранилась" },
  "gd.release": { lv: "Noņemt rezervāciju", en: "Release reservation", ru: "Снять резерв" },
  "gd.released": { lv: "Rezervācija noņemta", en: "Reservation released", ru: "Резерв снят" },
  "gd.resUntil": { lv: "rezervēts līdz", en: "reserved until", ru: "в резерве до" },
  "gd.reserved": { lv: "Rezervēts", en: "Reserved", ru: "В резерве" },
  "gd.search": { lv: "Nosaukums vai numurs", en: "Title or number", ru: "Название или номер" },
  "gd.sell": { lv: "Atzīmēt kā pārdotu", en: "Mark as sold", ru: "Отметить проданным" },
  "gd.show": { lv: "Rādīt skatlogā", en: "Show on the storefront", ru: "Показать на витрине" },
  "gd.showShort": { lv: "Rādīt", en: "Show", ru: "Показать" },
  "gd.shown": { lv: "Prece ir skatlogā", en: "Item is on the storefront", ru: "Товар на витрине" },
  "gd.sold": { lv: "Pārdots", en: "Sold", ru: "Продано" },
  "gd.soldTag": { lv: "pārdots", en: "sold", ru: "продано" },
  "gd.toArchive": { lv: "Uz arhīvu", en: "To archive", ru: "В архив" },
  "gd.toSale": { lv: "Uz pārdošanu", en: "To sale", ru: "В продажу" },
  "gd.unarchive": { lv: "Atgriezt no arhīva", en: "Restore from archive", ru: "Вернуть из архива" },
  "gd.unarchived": { lv: "Atgriezts no arhīva", en: "Restored from archive", ru: "Возвращено из архива" },
  "gd.unpick": { lv: "noņemt atlasi", en: "clear selection", ru: "снять отметки" },
  "gd.unsell": { lv: "Atgriezt pārdošanā", en: "Return to sale", ru: "Вернуть в продажу" },
  "gd.unsold": { lv: "Atgriezts pārdošanā", en: "Returned to sale", ru: "Вернули в продажу" },
  "h.created": { lv: "izveidots", en: "created", ru: "создан" },
  "h.delivered": { lv: "nodots pircējam", en: "handed to the buyer", ru: "передан покупателю" },
  "h.paidOut": { lv: "izmaksāts partnerim", en: "paid out to the partner", ru: "выплачено партнёру" },
  "h.refund": { lv: "atmaksa", en: "refund", ru: "возврат" },
  "h.release": { lv: "izmaksa kļūst pieejama", en: "payout unlocks", ru: "выплата разблокируется" },
  "h.shipped": { lv: "nosūtīts", en: "shipped", ru: "отправлен" },
  "imp.add": { lv: "+ Pievienot preci", en: "+ Add item", ru: "+ Добавить товар" },
  "imp.fail": { lv: "Imports neizdevās", en: "Import failed", ru: "Импорт не удался" },
  "imp.go": { lv: "Importēt", en: "Import", ru: "Импортировать" },
  "imp.hint": { lv: "Foto un apraksts tiks ielādēti automātiski — atliks tikai norādīt cenu.", en: "Photos and description are pulled in automatically — you only set the price.", ru: "Фото и описание подтянутся автоматически — вам останется поставить цену." },
  "imp.label": { lv: "Imports pēc saites — ielīmējiet preces adresi no izsoles", en: "Import by link — paste the item URL from the auction", ru: "Импорт по ссылке — вставьте адрес товара с аукциона" },
  "imp.manual": { lv: "+ Pievienot manuāli", en: "+ Add manually", ru: "+ Добавить вручную" },
  "log.back": { lv: "← uz skatlogu", en: "← to the storefront", ru: "← на витрину" },
  "log.bad": { lv: "Nepareizs lietotājvārds vai parole", en: "Wrong login or password", ru: "Неверный логин или пароль" },
  "log.busy": { lv: "Pieteikšanās…", en: "Signing in…", ru: "Вход…" },
  "log.in": { lv: "Pieteikties", en: "Sign in", ru: "Войти" },
  "log.login": { lv: "Lietotājvārds", en: "Login", ru: "Логин" },
  "log.pw": { lv: "Parole", en: "Password", ru: "Пароль" },
  "log.sub": { lv: "platformas un pārdevēju panelis", en: "platform and seller panel", ru: "кабинет площадки и продавцов" },
  "m.adres": { lv: "Adrese", en: "Address", ru: "Адрес" },
  "m.anketaNeZapolnena": { lv: "anketa nav aizpildīta", en: "form not filled in", ru: "анкета не заполнена" },
  "m.da": { lv: "jā", en: "yes", ru: "да" },
  "m.dogovor": { lv: "Līgums", en: "Contract", ru: "Договор" },
  "m.gotovo": { lv: "gatavs", en: "done", ru: "готово" },
  "m.kontakt": { lv: "Kontakts", en: "Contact", ru: "Контакт" },
  "m.nePrinyalUsloviya": { lv: "nav apstiprinājis noteikumus", en: "terms not accepted", ru: "не принял условия" },
  "m.nePrinyat": { lv: "nav pieņemts", en: "not accepted", ru: "не принят" },
  "m.net": { lv: "nē", en: "no", ru: "нет" },
  "m.netSchetaStripe": { lv: "nav Stripe konta", en: "no Stripe account", ru: "нет счёта Stripe" },
  "m.partnerovSProdazhami": { lv: "Partneru ar pārdevumiem pagaidām nav.", en: "No partners with sales yet.", ru: "Партнёров с продажами пока нет." },
  "m.peredan": { lv: "Nodots", en: "Handed over", ru: "Передан" },
  "m.predstavitel": { lv: "Pārstāvis", en: "Representative", ru: "Представитель" },
  "m.prichinaBloka": { lv: "Bloķēšanas iemesls", en: "Block reason", ru: "Причина блока" },
  "m.prinyat": { lv: "Pieņemts", en: "Accepted", ru: "Принят" },
  "m.priostanovlen": { lv: "apturēts", en: "suspended", ru: "приостановлен" },
  "m.prodavcovPokaNet": { lv: "Pārdevēju pagaidām nav.", en: "No sellers yet.", ru: "Продавцов пока нет." },
  "m.prohoditStripe": { lv: "iziet Stripe pārbaudi", en: "in Stripe review", ru: "проходит Stripe" },
  "m.regNomer": { lv: "Reģ. Nr.", en: "Reg. number", ru: "Рег. номер" },
  "m.rekvizity": { lv: "Rekvizīti", en: "Bank details", ru: "Реквизиты" },
  "m.schet": { lv: "Konts", en: "Account", ru: "Счёт" },
  "m.schetNeSozdan": { lv: "konts nav izveidots", en: "account not created", ru: "счёт не создан" },
  "m.sostoyanie": { lv: "Statuss", en: "Status", ru: "Состояние" },
  "m.spor": { lv: "strīds", en: "dispute", ru: "спор" },
  "m.srok": { lv: "Termiņš", en: "Term", ru: "Срок" },
  "m.stripeDostupnoV": { lv: "Stripe: pieejams / ceļā", en: "Stripe: available / in transit", ru: "Stripe: доступно / в пути" },
  "m.stripeZhdet": { lv: "Stripe gaida", en: "Stripe is waiting", ru: "Stripe ждёт" },
  "m.torguet": { lv: "tirgojas", en: "trading", ru: "торгует" },
  "m.tovar": { lv: "Prece", en: "Item", ru: "Товар" },
  "m.uderzhano": { lv: "Aizturēts", en: "Held", ru: "Удержано" },
  "m.uderzhano2": { lv: "aizturēts", en: "held", ru: "удержано" },
  "m.versiya": { lv: "Versija", en: "Version", ru: "Версия" },
  "m.vnimanie": { lv: "Uzmanību", en: "Attention", ru: "Внимание" },
  "m.vyplacheno": { lv: "Izmaksāts", en: "Paid out", ru: "Выплачено" },
  "m.zapolnyaetAnketu": { lv: "aizpilda anketu", en: "filling in the form", ru: "заполняет анкету" },
  "m.zhdetProverki": { lv: "gaida pārbaudi", en: "awaiting review", ru: "ждёт проверки" },
  "nav.exit": { lv: "Iziet", en: "Sign out", ru: "Выйти" },
  "nav.goods": { lv: "Preces", en: "Items", ru: "Товары" },
  "nav.orders": { lv: "Pasūtījumi", en: "Orders", ru: "Заказы" },
  "nav.payouts": { lv: "Izmaksas", en: "Payouts", ru: "Выплаты" },
  "nav.sellers": { lv: "Pārdevēji", en: "Sellers", ru: "Продавцы" },
  "nav.settings": { lv: "Iestatījumi", en: "Settings", ru: "Настройки" },
  "nav.shop": { lv: "Skatlogs ↗", en: "Storefront ↗", ru: "Витрина ↗" },
  "nav.stats": { lv: "Statistika", en: "Statistics", ru: "Статистика" },
  "o.fajlVygruzhenOtkryvaetsya": { lv: "Fails eksportēts — atveras Excel un Numbers", en: "File exported — opens in Excel and Numbers", ru: "Файл выгружен — открывается в Excel и Numbers" },
  "o.inacheKomissiyuPoteryaet": { lv: "Citādi komisiju zaudēs partneris: Stripe to neatmaksā automātiski", en: "Otherwise the partner loses the commission: Stripe does not refund it automatically", ru: "Иначе комиссию потеряет партнёр: Stripe не возвращает её автоматически" },
  "o.oplachenoCentsLeft": { lv: ")} · apmaksāts {cents === left ? ", en: ")} · paid {cents === left ? ", ru: ")} · оплачено {cents === left ? " },
  "o.otmetteTakEsli": { lv: "Atzīmējiet tā, ja nauda saņemta skaidrā naudā vai ar pārskaitījumu ārpus Stripe.", en: "Mark it this way if the money came in cash or by transfer outside Stripe.", ru: "Отметьте так, если деньги пришли наличными или переводом мимо Stripe." },
  "o.otpravlenoDateO": { lv: ">Nosūtīts {date(o.shippedAt)}{o.shipping?.tracking ? ` · ${o.shipping.tracking}` : ", en: ">Shipped {date(o.shippedAt)}{o.shipping?.tracking ? ` · ${o.shipping.tracking}` : ", ru: ">Отправлено {date(o.shippedAt)}{o.shipping?.tracking ? ` · ${o.shipping.tracking}` : " },
  "o.tovarStanetProdan": { lv: "Prece tiks atzīmēta kā pārdota, un sāksies partnera izmaksas aprēķins.", en: "The item becomes sold, and the partner's payout starts accruing.", ru: "Товар станет продан, партнёру начнёт считаться выплата." },
  "o.vernutIKomissiyu": { lv: "Atmaksāt arī SOFA.LV komisijas maksu", en: "Refund the platform commission too", ru: "Вернуть и комиссию площадки" },
  "o.zapisIscheznetNavsegda": { lv: "Ieraksts pazudīs neatgriezeniski, preces atgriezīsies skatlogā. Atskaitēm labāk atzīmēt «atcelts».", en: "The record disappears for good, items return to the storefront. For reporting it is better to mark it «cancelled».", ru: "Запись исчезнет навсегда, товары вернутся на витрину. Для отчётности лучше отметить «отменён»." },
  "ord.allDone": { lv: "Viss nokārtots ✓", en: "All handled ✓", ru: "Всё разобрано ✓" },
  "ord.anyDelivery": { lv: "Jebkura saņemšana", en: "Any receiving method", ru: "Любое получение" },
  "ord.anyStatus": { lv: "Jebkurš statuss", en: "Any status", ru: "Любой статус" },
  "ord.brokenText": { lv: "teksts bojāts ievadot", en: "text corrupted on input", ru: "текст повреждён при вводе" },
  "ord.buyer": { lv: "Pircējs", en: "Buyer", ru: "Покупатель" },
  "ord.carrier": { lv: "Pārvadātājs (DPD, Omniva, savs)", en: "Carrier (DPD, Omniva, own)", ru: "Перевозчик (DPD, Omniva, свой)" },
  "ord.chipPayout": { lv: "Gatavi izmaksai", en: "Ready for payout", ru: "Готовы к выплате" },
  "ord.chipRefund": { lv: "Atmaksas", en: "Refunds", ru: "Возвраты" },
  "ord.chipShip": { lv: "Gaida nosūtīšanu", en: "Awaiting shipping", ru: "Ждут отправки" },
  "ord.chipUnpaid": { lv: "Gaida apmaksu", en: "Awaiting payment", ru: "Ждут оплаты" },
  "ord.comment": { lv: "Komentārs", en: "Comment", ru: "Комментарий" },
  "ord.copied": { lv: "Dati kurjeram nokopēti", en: "Courier details copied", ru: "Данные для курьера скопированы" },
  "ord.copyCourier": { lv: "Kopēt kurjeram", en: "Copy for courier", ru: "Скопировать для курьера" },
  "ord.csv": { lv: "Eksportēt CSV", en: "Export CSV", ru: "Выгрузить CSV" },
  "ord.csvFail": { lv: "Eksports neizdevās", en: "Export failed", ru: "Выгрузка не удалась" },
  "ord.delete": { lv: "Dzēst pasūtījumu", en: "Delete order", ru: "Удалить заказ" },
  "ord.delivery": { lv: "Piegāde", en: "Delivery", ru: "Доставка" },
  "ord.empty": { lv: "Pasūtījumu pagaidām nav", en: "No orders yet", ru: "Заказов пока нет" },
  "ord.emptyFiltered": { lv: "Filtriem nekas neatbilst", en: "Nothing matches the filters", ru: "Под фильтры ничего не подошло" },
  "ord.emptyFilteredHint": { lv: "Notīriet filtrus, lai redzētu visus pasūtījumus.", en: "Clear the filters to see all orders.", ru: "Сбросьте фильтры, чтобы увидеть все заказы." },
  "ord.emptyHint": { lv: "Šeit parādīsies pasūtījumi no skatloga — uzreiz ar pircēja kontaktiem.", en: "Orders from the storefront appear here — with buyer contacts included.", ru: "Здесь появятся заказы с витрины — сразу с контактами покупателя." },
  "ord.gross": { lv: "Apgrozījums", en: "Turnover", ru: "Оборот" },
  "ord.history": { lv: "Vēsture", en: "History", ru: "История" },
  "ord.items": { lv: "Pozīcijas", en: "Items", ru: "Позиции" },
  "ord.map": { lv: "Adrese kartē", en: "Address on map", ru: "Адрес на карте" },
  "ord.markDelivered": { lv: "Nodots pircējam →", en: "Handed to the buyer →", ru: "Передан покупателю →" },
  "ord.markPaid": { lv: "Atzīmēt kā apmaksātu", en: "Mark as paid", ru: "Отметить оплаченным" },
  "ord.markPaidYes": { lv: "Jā, apmaksāts", en: "Yes, paid", ru: "Да, оплачен" },
  "ord.more": { lv: "Vēl", en: "More", ru: "Ещё" },
  "ord.noAddress": { lv: "adrese nav norādīta", en: "no address given", ru: "адрес не указан" },
  "ord.notePh": { lv: "Piemēram: paņems sestdien pēc 14:00", en: "For example: picking up on Saturday after 14:00", ru: "Например: заберёт в субботу после 14:00" },
  "ord.noteSave": { lv: "Pierakstīt", en: "Save note", ru: "Записать" },
  "ord.notes": { lv: "Piezīmes", en: "Notes", ru: "Заметки" },
  "ord.ourFee": { lv: "Mūsu komisija", en: "Our commission", ru: "Наша комиссия" },
  "ord.payLink": { lv: "Apmaksas saite", en: "Payment link", ru: "Ссылка на оплату" },
  "ord.shownOf": { lv: "Rādīti {n} no {total} · par summu {sum}", en: "Showing {n} of {total} · total {sum}", ru: "Показано {n} из {total} · на сумму {sum}" },
  "f.from": { lv: "€ no", en: "€ from", ru: "€ от" },
  "f.to": { lv: "€ līdz", en: "€ to", ru: "€ до" },
  "ord.pcs1": { lv: "{n} pozīcija", en: "{n} item", ru: "{n} поз." },
  "ord.pcs": { lv: "{n} pozīcijas", en: "{n} items", ru: "{n} поз." },
  "ord.pickup": { lv: "Saņemšana klātienē", en: "Pickup", ru: "Самовывоз" },
  "ord.pickupFull": { lv: "Saņemšana klātienē noliktavā Talsos (bez maksas)", en: "Pickup from the warehouse in Talsi (free)", ru: "Самовывоз со склада в Талси (бесплатно)" },
  "ord.reason": { lv: "Iemesls", en: "Reason", ru: "Причина" },
  "ord.reasonCustomer": { lv: "Pircējs atteicās", en: "Buyer declined", ru: "Покупатель отказался" },
  "ord.reasonDuplicate": { lv: "Dubulta apmaksa", en: "Duplicate payment", ru: "Двойная оплата" },
  "ord.reasonFraud": { lv: "Aizdomas par krāpšanu", en: "Suspected fraud", ru: "Подозрение на мошенничество" },
  "ord.receiving": { lv: "Saņemšana", en: "Receiving", ru: "Получение" },
  "ord.refundAll": { lv: "Visa summa", en: "Full amount", ru: "Вся сумма" },
  "ord.refundAmount": { lv: "Atmaksas summa, €", en: "Refund amount, €", ru: "Сумма возврата, €" },
  "ord.refundFail": { lv: "Atmaksa neizdevās", en: "Refund failed", ru: "Возврат не прошёл" },
  "ord.refundGoods": { lv: "Tikai prece", en: "Item only", ru: "Только товар" },
  "ord.refundOpen": { lv: "Atmaksāt naudu…", en: "Refund money…", ru: "Вернуть деньги…" },
  "ord.refundShipping": { lv: "Tikai piegāde", en: "Delivery only", ru: "Только доставка" },
  "ord.refunding": { lv: "Atmaksājam…", en: "Refunding…", ru: "Возвращаем…" },
  "ord.restock": { lv: "Atgriezt preces skatlogā", en: "Return items to the storefront", ru: "Вернуть товары на витрину" },
  "ord.search": { lv: "Numurs, vārds, e-pasts, tālrunis, adrese, prece", en: "Number, name, email, phone, address, item", ru: "Номер, имя, почта, телефон, адрес, товар" },
  "ord.shipSaved": { lv: "Nosūtīšana saglabāta", en: "Shipping saved", ru: "Отправка записана" },
  "ord.shipToUs": { lv: "Piegāde mums", en: "Delivery to us", ru: "Доставка нам" },
  "ord.shipped": { lv: "Nosūtīts", en: "Shipped", ru: "Отправлено" },
  "ord.shipping": { lv: "Nosūtīšana", en: "Shipping", ru: "Отправка" },
  "ord.toPartner": { lv: "Partnerim", en: "To partner", ru: "Партнёру" },
  "ord.tracking": { lv: "Izsekošanas numurs", en: "Tracking number", ru: "Трек-номер" },
  "ord.unDeliver": { lv: "Noņemt nodošanas atzīmi", en: "Remove handover mark", ru: "Снять отметку о передаче" },
  "ord.update": { lv: "Atjaunināt", en: "Update", ru: "Обновить" },
  "ord.yourItems": { lv: "Jūsu pozīcijas", en: "Your items", ru: "Ваши позиции" },
  "role.admin": { lv: "platforma", en: "platform", ru: "площадка" },
  "role.seller": { lv: "pārdevējs", en: "seller", ru: "продавец" },
  "s.adresSamovyvoza": { lv: "Saņemšanas adrese", en: "Pickup address", ru: "Адрес самовывоза" },
  "s.adresVPole": { lv: "adrese sūtītāja laukā", en: "address in the «from» field", ru: "адрес в поле «от кого»" },
  "s.avtoperevodKartochek": { lv: "Kartīšu autotulkošana", en: "Auto-translate cards", ru: "Автоперевод карточек" },
  "s.beretsyaSCeny": { lv: "tiek ieturēta no jauno partneru preces cenas", en: "taken from the item price of new partners", ru: "берётся с цены товара новых партнёров" },
  "s.dlyaPisemO": { lv: "e-pastiem par pasūtījumiem", en: "for order emails", ru: "для писем о заказах" },
  "s.dnej": { lv: "dienas", en: "days", ru: "дней" },
  "s.dnejPoslePeredachi": { lv: "dienas pēc preces nodošanas pircējam", en: "days after the item is handed to the buyer", ru: "дней после передачи товара покупателю" },
  "s.dostavkaPoLatvii": { lv: "Piegāde Latvijā", en: "Delivery within Latvia", ru: "Доставка по Латвии" },
  "s.izOkruzheniyaServera": { lv: "no servera vides", en: "from the server environment", ru: "из окружения сервера" },
  "s.kanalNeRabotaet": { lv: "Kanāls nedarbojas", en: "Channel is down", ru: "Канал не работает" },
  "s.kartochkiPerevodyatsyaNa": { lv: "kartītes tiek tulkotas trīs valodās saglabāšanas brīdī", en: "cards are translated into three languages on save", ru: "карточки переводятся на три языка при сохранении" },
  "s.klyuchDeepseek": { lv: "DeepSeek atslēga", en: "DeepSeek key", ru: "ключ DeepSeek" },
  "s.klyuchDeepseek2": { lv: "DeepSeek atslēga", en: "DeepSeek key", ru: "Ключ DeepSeek" },
  "s.klyuchResend": { lv: "Resend atslēga", en: "Resend key", ru: "Ключ Resend" },
  "s.klyuchStripeZadan": { lv: "Stripe atslēga norādīta serverī", en: "Stripe key is set on the server", ru: "ключ Stripe задан на сервере" },
  "s.kudaPrihodyatUvedomleniya": { lv: "kur pienāk paziņojumi", en: "where notifications arrive", ru: "куда приходят уведомления" },
  "s.menyayutsyaBezPerezapuska": { lv: "Mainās bez servera pārstartēšanas. Atslēgas var atstāt vidē — tad laukā redzams «no servera vides».", en: "Change without restarting the server. Keys can stay in the environment — then the field shows «from the server environment».", ru: "Меняются без перезапуска сервера. Ключи можно оставить в окружении — тогда поле показывает «из окружения сервера»." },
  "s.min": { lv: "min", en: "min", ru: "мин" },
  "s.napishiteBotuI": { lv: "uzrakstiet botam un paņemiet id no @userinfobot", en: "message the bot and take the id from @userinfobot", ru: "напишите боту и возьмите id из @userinfobot" },
  "s.nastrojkiNeZagruzilis": { lv: "Iestatījumi neielādējās", en: "Settings failed to load", ru: "Настройки не загрузились" },
  "s.nastrojkiPloschadki": { lv: "Platformas iestatījumi", en: "Platform settings", ru: "Настройки площадки" },
  "s.nastrojkiSohraneny": { lv: "Iestatījumi saglabāti", en: "Settings saved", ru: "Настройки сохранены" },
  "s.neNastroeno": { lv: "nav iestatīts", en: "not configured", ru: "не настроено" },
  "s.neZadan": { lv: "nav norādīts", en: "not set", ru: "не задан" },
  "s.ostavtePustymNe": { lv: "••••••••  (atstājiet tukšu — nemainīt)", en: "••••••••  (leave empty — no change)", ru: "••••••••  (оставьте пустым — не менять)" },
  "s.otmenit": { lv: "atcelt", en: "cancel", ru: "отменить" },
  "s.otpravitTestovoePismo": { lv: "Sūtīt testa e-pastu", en: "Send test email", ru: "Отправить тестовое письмо" },
  "s.otpravitTestovoeSoobschenie": { lv: "Sūtīt testa ziņu", en: "Send test message", ru: "Отправить тестовое сообщение" },
  "s.otpravitel": { lv: "Sūtītājs", en: "Sender", ru: "Отправитель" },
  "s.otpravlyaem": { lv: "Sūtām…", en: "Sending…", ru: "Отправляем…" },
  "s.perevodKartochek": { lv: "Kartīšu tulkošana", en: "Card translation", ru: "Перевод карточек" },
  "s.pismoOtpravleno": { lv: "E-pasts nosūtīts", en: "Email sent", ru: "Письмо отправлено" },
  "s.poUmolchaniyu": { lv: "pēc noklusējuma", en: "default", ru: "по умолчанию" },
  "s.pochtaDlyaZakazov": { lv: "E-pasts pasūtījumiem", en: "Email for orders", ru: "Почта для заказов" },
  "s.podtverzhdenieOplaty": { lv: "Maksājuma apstiprinājums", en: "Payment confirmation", ru: "Подтверждение оплаты" },
  "s.pokazyvaetsyaPokupatelyuPri": { lv: "redzams pircējam noformēšanas laikā", en: "shown to the buyer at checkout", ru: "показывается покупателю при оформлении" },
  "s.pokazyvaetsyaPriOformlenii": { lv: "redzams pasūtījuma noformēšanā", en: "shown at checkout", ru: "показывается при оформлении заказа" },
  "s.poluchiteUBotfather": { lv: "saņemiet no @BotFather", en: "get it from @BotFather", ru: "получите у @BotFather" },
  "s.priemPlatezhej": { lv: "Maksājumu pieņemšana", en: "Accepting payments", ru: "Приём платежей" },
  "s.rezhimStripe": { lv: "Stripe režīms", en: "Stripe mode", ru: "Режим Stripe" },
  "s.boevojRezhim": { lv: "Reālie maksājumi", en: "Live", ru: "Боевой" },
  "s.pesochnica": { lv: "Smilšu kaste", en: "Sandbox", ru: "Песочница" },
  "s.pesochnicaOpisanie": { lv: "Maksājumi notiek Stripe smilšu kastē: nauda nav īsta, kartes testa. Skatlogā redzams brīdinājums.", en: "Payments run in the Stripe sandbox: no real money, test cards only. A warning is shown on the storefront.", ru: "Платежи идут в песочнице Stripe: деньги ненастоящие, карты тестовые. На витрине висит предупреждение." },
  "s.boevojOpisanie": { lv: "Maksājumi notiek ar reālu naudu. Atslēgas ņemtas no servera vides.", en: "Payments are processed with real money. Keys come from the server environment.", ru: "Платежи идут на настоящих деньгах. Ключи берутся из окружения сервера." },
  "s.testovyjKlyuch": { lv: "Smilšu kastes atslēga (sk_test_…)", en: "Sandbox secret key (sk_test_…)", ru: "Ключ песочницы (sk_test_…)" },
  "s.testovyjKlyuchGde": { lv: "Stripe smilšu kastē: Developers → API keys → Secret key", en: "In the Stripe sandbox: Developers → API keys → Secret key", ru: "В песочнице Stripe: Developers → API keys → Secret key" },
  "s.testovyjVebhuk": { lv: "Smilšu kastes webhook (platformas)", en: "Sandbox webhook secret (platform)", ru: "Вебхук песочницы (площадки)" },
  "s.testovyjVebhukGde": { lv: "Izveidojam automātiski, kad ieslēdzat smilšu kasti", en: "Created automatically when you enable the sandbox", ru: "Создаётся автоматически при включении песочницы" },
  "s.testovyjVebhukConnect": { lv: "Smilšu kastes webhook (partneru konti)", en: "Sandbox webhook secret (connected accounts)", ru: "Вебхук песочницы (счета партнёров)" },
  "s.testovyjVebhukConnectGde": { lv: "Tas pats — izveidojam automātiski", en: "Same — created automatically", ru: "То же — создаётся автоматически" },
  "s.snachalaKlyuch": { lv: "Vispirms ievadiet un saglabājiet smilšu kastes atslēgu", en: "Enter and save the sandbox key first", ru: "Сначала введите и сохраните ключ песочницы" },
  "s.podtverditPesochnicu": { lv: "Pārslēgt veikalu uz Stripe smilšu kasti? Reāli maksājumi netiks pieņemti, līdz pārslēgsiet atpakaļ.", en: "Switch the shop to the Stripe sandbox? Real payments will not be accepted until you switch back.", ru: "Перевести магазин в песочницу Stripe? Настоящие платежи приниматься не будут, пока не вернёте боевой режим." },
  "s.podtverditBoevoj": { lv: "Atgriezties pie reāliem maksājumiem?", en: "Switch back to live payments?", ru: "Вернуться к настоящим платежам?" },
  "s.vklyuchenaPesochnica": { lv: "Ieslēgta smilšu kaste", en: "Sandbox enabled", ru: "Включена песочница" },
  "s.vklyuchenBoevoj": { lv: "Ieslēgti reālie maksājumi", en: "Live payments enabled", ru: "Включён боевой режим" },
  "s.rezhimRaboty": { lv: "Darba režīms", en: "Mode", ru: "Режим работы" },
  "s.rezervNaOplatu": { lv: "Rezervācija apmaksai", en: "Reservation for payment", ru: "Резерв на оплату" },
  "s.skolkoDerzhimPredmet": { lv: "cik ilgi turam preci, kamēr pircējs maksā", en: "how long we hold the item while the buyer pays", ru: "сколько держим предмет, пока покупатель платит" },
  "s.sobytiyaPartnerov": { lv: "Partneru notikumi", en: "Partner events", ru: "События партнёров" },
  "s.sohranitIzmeneniya": { lv: "Saglabāt izmaiņas", en: "Save changes", ru: "Сохранить изменения" },
  "s.soobschenieOtpravlenoV": { lv: "Ziņa nosūtīta uz Telegram", en: "Message sent to Telegram", ru: "Сообщение отправлено в Telegram" },
  "s.tokenBotaTelegram": { lv: "Telegram bota tokens", en: "Telegram bot token", ru: "Токен бота Telegram" },
  "s.uderzhanieVyplaty": { lv: "Izmaksas aizturēšana", en: "Payout hold", ru: "Удержание выплаты" },
  "s.usloviyaRaboty": { lv: "Darba nosacījumi", en: "Working terms", ru: "Условия работы" },
  "s.uvedomleniyaNaPochtu": { lv: "E-pasta paziņojumi", en: "Email notifications", ru: "Уведомления на почту" },
  "s.uvedomleniyaOZakazah": { lv: "Paziņojumi par pasūtījumiem", en: "Order notifications", ru: "Уведомления о заказах" },
  "s.uvedomleniyaVTelegram": { lv: "Telegram paziņojumi", en: "Telegram notifications", ru: "Уведомления в Telegram" },
  "s.vebhukConnect": { lv: "Connect webhook", en: "Connect webhook", ru: "вебхук Connect" },
  "s.vebhukPloschadki": { lv: "platformas webhook", en: "platform webhook", ru: "вебхук площадки" },
  "s.zadan": { lv: "norādīts", en: "set", ru: "задан" },
  "s.zadanoZdes": { lv: "norādīts šeit", en: "set here", ru: "задано здесь" },
  "s.zakazyPrihodyatPismom": { lv: "pasūtījumi pienāk e-pastā", en: "orders arrive by email", ru: "заказы приходят письмом" },
  "s.zakazyPrihodyatV": { lv: "pasūtījumi pienāk čatā", en: "orders arrive in the chat", ru: "заказы приходят в чат" },
  "sel.partner": { lv: "partneris", en: "partner", ru: "партнёр" },
  "sel.shop": { lv: "veikala skatlogs", en: "shop storefront", ru: "витрина магазина" },
  "sel.shop2": { lv: "Veikala skatlogs", en: "Shop storefront", ru: "Витрина магазина" },
  "sl.access": { lv: "Piekļuve", en: "Access", ru: "Доступ" },
  "sl.active": { lv: "Piekļuve aktīva", en: "Access active", ru: "Доступ активен" },
  "sl.add": { lv: "+ Pievienot pārdevēju", en: "+ Add seller", ru: "+ Добавить продавца" },
  "sl.commission": { lv: "SOFA.LV komisijas maksa, %", en: "Platform commission, %", ru: "Комиссия площадки, %" },
  "sl.contact": { lv: "Kontakti (tālrunis, e-pasts)", en: "Contact (phone, email)", ru: "Контакт (телефон, почта)" },
  "sl.delete": { lv: "Dzēst", en: "Delete", ru: "Удалить" },
  "sl.login": { lv: "Lietotājvārds", en: "Login", ru: "Логин для входа" },
  "sl.name": { lv: "Vārds / veikals", en: "Name / shop", ru: "Имя / магазин" },
  "sl.new": { lv: "Jauns pārdevējs", en: "New seller", ru: "Новый продавец" },
  "sl.off": { lv: "piekļuve izslēgta", en: "access disabled", ru: "доступ выключен" },
  "sl.saved": { lv: "Pārdevējs saglabāts", en: "Seller saved", ru: "Продавец сохранён" },
  "sl.title": { lv: "Platformas pārdevēji", en: "Platform sellers", ru: "Продавцы площадки" },
  "st.cancelled": { lv: "atcelts", en: "cancelled", ru: "отменён" },
  "st.done": { lv: "izpildīts", en: "completed", ru: "выполнен" },
  "st.expired": { lv: "termiņš beidzies", en: "expired", ru: "просрочен" },
  "st.new": { lv: "gaida apmaksu", en: "awaiting payment", ru: "ждёт оплаты" },
  "st.newShort": { lv: "neapmaksāts", en: "unpaid", ru: "не оплачен" },
  "st.paid": { lv: "apmaksāts", en: "paid", ru: "оплачен" },
  "stt.commission": { lv: "Komisija", en: "Commission", ru: "Комиссия" },
  "stt.date": { lv: "Datums", en: "Date", ru: "Дата" },
  "stt.fee": { lv: "Mūsu komisija", en: "Our commission", ru: "Наша комиссия" },
  "stt.feeHint": { lv: "aizturēts no pārdevējiem", en: "held from sellers", ru: "удержано с продавцов" },
  "stt.gross": { lv: "Apmaksātais apgrozījums", en: "Paid turnover", ru: "Оборот оплаченных" },
  "stt.netHint": { lv: "neto", en: "net", ru: "чистыми" },
  "stt.order": { lv: "Pasūtījums", en: "Order", ru: "Заказ" },
  "stt.payout": { lv: "Izmaksai pārdevējiem", en: "Payable to sellers", ru: "К выплате продавцам" },
  "stt.pending": { lv: "Gaida apmaksu", en: "Awaiting payment", ru: "Ожидает оплаты" },
  "stt.pendingHint": { lv: "jaunie pasūtījumi", en: "new orders", ru: "новые заказы" },
  "stt.products": { lv: "Preces", en: "Items", ru: "Товаров" },
  "stt.seller": { lv: "Pārdevējs", en: "Seller", ru: "Продавец" },
  "stt.sold": { lv: "Pārdots", en: "Sold", ru: "Продано" },
  "stt.toYou": { lv: "Jums", en: "To you", ru: "Вам" },
  "stt.waiting": { lv: "Gaidīšanā", en: "Pending", ru: "В ожидании" },
  "stt.yourNet": { lv: "Jūsu neto ieņēmumi", en: "Your net earnings", ru: "Ваш чистый заработок" },
  "ui.cancel": { lv: "Atcelt", en: "Cancel", ru: "Отмена" },
  "ui.close": { lv: "Aizvērt", en: "Close", ru: "Закрыть" },
  "ui.confirm": { lv: "Apstiprināt", en: "Confirm", ru: "Подтвердить" },
  "ui.copy": { lv: "kopēt", en: "copy", ru: "копировать" },
  "ui.error": { lv: "Kļūda", en: "Error", ru: "Ошибка" },
  "ui.expired": { lv: "Sesija beigusies — piesakieties vēlreiz", en: "Session expired — sign in again", ru: "Сессия истекла — войдите заново" },
  "ui.failed": { lv: "Neizdevās", en: "Failed", ru: "Не получилось" },
  "ui.justNow": { lv: "tikko", en: "just now", ru: "только что" },
  "ui.loadFail": { lv: "Neizdevās ielādēt datus", en: "Failed to load data", ru: "Не удалось загрузить данные" },
  "ui.minAgo": { lv: "pirms minūtes", en: "a minute ago", ru: "минуту назад" },
  "ui.retry": { lv: "Atkārtot", en: "Retry", ru: "Повторить" },
  "ui.saveFail": { lv: "Nesaglabājās", en: "Not saved", ru: "Не сохранилось" },
};
